[package]
name = "jwtutil"
version = "0.1.0"
edition = "2021"

# Add dependencies
[dependencies]
clap = "2.33"
jwt = "0.16"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
colored_json = "3.2.0"
chrono = "0.4.26"
